### ISSUE TITLE
Build issue on Windows

### ISSUE THREAD

**Issue by sonic0002** [luisbebop/mruby-polarssl#11]
While trying to build the gem using VS 2013, below error is seen

(in C:/Personal/PlatformWork/Features/Feature301710ChangeChefClientInstallerFromPushToPull/mruby-1.3.0/mruby-1.3.0)
CC    build/mrbgems/mruby-polarssl/src/polarssl.c -> build/host/mrbgems/mruby-polarssl/src/polarssl.obj
cl : Command line error D8004 : '/W' requires an argument
cl : Command line error D8004 : '/W' requires an argument
rake aborted!
Command Failed: [cl.exe /c /nologo /W3 /we4013 /Zi /MD /O2 /D_CRT_SECURE_NO_WARNINGS -D_FILE_OFFSET_BITS=64 -Wall -W -Wdeclaration-after-statement /DMRB_STACK_EXTEND_DOUBLING /DMRB_DEBUG /DMRBGEM_MRUB
Y_POLARSSL_VERSION=0.0.0 /I"C:\Personal\PlatformWork\Features\Feature301710ChangeChefClientInstallerFromPushToPull\mruby-1.3.0\mruby-1.3.0\include" /I"C:\Personal\PlatformWork\Features\Feature301710Ch
angeChefClientInstallerFromPushToPull\mruby-1.3.0\mruby-1.3.0\build\mrbgems\mruby-polarssl\polarssl\include" /I"C:\Personal\PlatformWork\Features\Feature301710ChangeChefClientInstallerFromPushToPull\m
ruby-1.3.0\mruby-1.3.0\build\mrbgems\mruby-polarssl\polarssl\..\..\mruby-io\include" /I"C:\Personal\PlatformWork\Features\Feature301710ChangeChefClientInstallerFromPushToPull\mruby-1.3.0\mruby-1.3.0\s
rc" /I"C:\Personal\PlatformWork\Features\Feature301710ChangeChefClientInstallerFromPushToPull\mruby-1.3.0\mruby-1.3.0\build\mrbgems\mruby-io\include" /Fo"C:\Personal\PlatformWork\Features\Feature30171
0ChangeChefClientInstallerFromPushToPull\mruby-1.3.0\mruby-1.3.0\build\host\mrbgems\mruby-polarssl\src\polarssl.obj" "C:\Personal\PlatformWork\Features\Feature301710ChangeChefClientInstallerFromPushTo
Pull\mruby-1.3.0\mruby-1.3.0\build\mrbgems\mruby-polarssl\src\polarssl.c"]

This indicates that some flags are incorrect.  Can you help take a look?

OS : Windows 7
VS : 2013

**Comment by scalone** [comment]
Hey @sonic0002 are you still having this problem?
