### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by Asmod4n** [luisbebop/mruby-polarssl#2]
I dunno what changed, but `ssl.handshake` throws a TypeError, something expects a Class but gets a Module.

**Comment by scalone** [comment]
Hey @Asmod4n, sorry for the late response. I've fixed the bug(supporting mruby 1.1.0), can you check if it still happening, please?

**Comment by Asmod4n** [comment]
make exits with this now

```
CC    build/host/mrbgems/mruby-polarssl/gem_init.c -> build/host/mrbgems/mruby-polarssl/gem_init.o
rake aborted!
Don't know how to rake mruby/build/host/mrbgems/mruby-polarssl/polarssl/library/aes.o
```

**Comment by scalone** [comment]
@Asmod4n I added polarssl as a submodule, please execute:
`git submodule init`
`git submodule update`

**Comment by Asmod4n** [comment]
Had to change .gitmodules and .git/config to use https:// instead of git@ or else i wouldn't have read access.

**Comment by Asmod4n** [comment]
But aside from that it works again :)
