### ISSUE TITLE
polarssl submodule causing trouble to the mrbgem?

### ISSUE THREAD

**Issue by rubiojr** [luisbebop/mruby-polarssl#3]
It seems that the build config no longer works after removing polarssl code in favor of the submodule:

My fork works however, where the code is still included:

```
MRuby::Build.new do |conf|

    # ... (snip) ...

    conf.gem :git => 'https://github.com/rubiojr/mruby-polarssl.git'
end
```

Perhaps there's a way to make the submodule work and I'm not aware of it?

**Comment by scalone** [comment]
Hey @rubiojr I'm waiting for this pull request to be accepted:
https://github.com/mruby/mruby/pull/2862
Then we will be able to work with polarssl, as submodule, without problems.

**Comment by rubiojr** [comment]
Awesome, sounds like a good idea.

**Comment by scalone** [comment]
@hey @rubiojr, matz accepted the pull request, so I'm considering this close, ok?

**Comment by rubiojr** [comment]
Thanks @scalone!
